version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ai_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./requirements.txt:/app/requirements.txt
      - ./docker/.env:/app/.env
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: ai_frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./frontend:/app/frontend
      - ./docker/.env:/app/.env
    command: streamlit run frontend/app_streamlit.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped
    depends_on:
      - backend
